### ISSUE TITLE
Multicam plugin not able to switch between cameras

### ISSUE THREAD

**Issue by Jarren141** [jneilliii/OctoPrint-ConsolidatedTabs#26] opened 2020-09-17 21:40 UTC
Your plugin is awesome but there is this one bug that could be improved. 

The plugin only switches views if I switch tabs on chrome and come back to octoprint but reloading the page with a different camera results in the default webcam being displayed.

The Plugin manager shows
"Consolidated Tabs (0.1.2)
 Homepage  jneilliii
Combines configured tabs into a single tab.
 AGPLv3  Python >=2.7,<4  "

![image](https://user-images.githubusercontent.com/69659296/93530698-9fd55d80-f903-11ea-8d9e-c140547a2101.png)
![image](https://user-images.githubusercontent.com/69659296/93530767-be3b5900-f903-11ea-9298-7e02fdbe0c26.png)

**Comment by Jarren141** [comment] 2020-09-17 21:41
Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by jneilliii** [comment] 2020-09-18 01:36
Duplicate of #20 I submitted a PR to that plugin's repo that will resolve this issue for you. See the details in the closed issue.

**Closed by jneilliii** 2020-09-18 01:36 UTC

**Comment by jneilliii** [comment] 2020-09-18 02:42
I just checked and my changes were merged within that plugin repo, but there was not a new version released. You should be able to uninstall the plugin keeping the settings and reinstall the multicam plugin and get the newer version that should work with this plugin.

**Comment by Jarren141** [comment] 2020-09-21 18:34
Thanks so much! Sorry to make a duplicate. this was my first ever "issues" thing. Totally fixed the issue!
