### ISSUE TITLE
[FR]: Enable multiple "consolidated" tabs to allow for different "scenes"

### ISSUE THREAD

**Issue by puterboy** [jneilliii/OctoPrint-ConsolidatedTabs#52] opened 2022-08-08 19:08 UTC
First, thanks for another GREAT PLUGIN.
Would be great if it would be possible to create alternative consolidation or scenes for different situations.
For example,

- For printing, I like to see the Temperature, Control, and Dashboard tabs
- For bed leveling, I like to see the Temperature and Bed Visualizer tabs
etc.

Also, in line with this notion of scenes, it would be great if you had the option to still see some of the consolidated tabs individually as unconsolidated tabs. For example, if I want a large version of the temperature history, I may want to see it full screen without being part of a tab collage.

Just a wish list item :)

**Comment by jneilliii** [comment] 2022-08-08 20:19
duplicate of #5

**Closed by jneilliii** 2022-08-08 20:19 UTC
